"""add orders and order items tables

Revision ID: 622b5ab7e433
Revises: f9ef751f5b2c
Create Date: 2026-09-25 20:32:00.512053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '622b5ab7e433'
down_revision: Union[str, Sequence[str], None] = 'f9ef751f5b2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('books', 'author',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('books', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('books', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_books_title'), table_name='books')
    op.drop_constraint(op.f('books_owner_id_fkey'), 'books', type_='foreignkey')
    op.create_foreign_key(None, 'books', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_column('books', 'description')
    op.add_column('users', sa.Column('email', sa.String(), nullable=False))
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=False))
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'username')
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'email')
    op.add_column('books', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.create_foreign_key(op.f('books_owner_id_fkey'), 'books', 'users', ['owner_id'], ['id'])
    op.create_index(op.f('ix_books_title'), 'books', ['title'], unique=False)
    op.alter_column('books', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('books', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('books', 'author',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('books', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
